apiVersion: v2
name: rancher-cluster-templates
version: 0.7.1
appVersion: 0.7.1

type: application
description: Hardened Rancher Cluster Templates by Rancher Government
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg

home: https://github.com/rancherfederal
sources:
  - https://github.com/rancherfederal/rancher-cluster-templates

maintainers:
  - name: Rancher Government
    email: support@ranchergovernment.com
    url: https://ranchergovernment.com

annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
  classification: UNCLASSIFIED
